### ISSUE TITLE
Plugin uninstallation issue

### ISSUE THREAD

**Issue by alixiaodi** [darkospoljaric/plugin-platform#2]
Boss, your code is indeed impressive, but I have a problem. How can a jar that has already been loaded into the jvm be uninstalled? If I manually delete that file, it will prompt that it cannot be deleted while in use

**Comment by darkospoljaric** [comment]
Glad you found it useful!

All the input streams opened by the `PluginClassloader` would have to be closed with `jarFile.close()`. Only then you'll be able to delete the file. However, classes that are already loaded would stay on the heap and you would be able to use them.

**Comment by alixiaodi** [comment]
File deletion is not important to me. How can I remove a class that has already been loaded into memory? For example, if I load a "test. class" with a specified interface function, how can I delete it now that I don't want it to be used externally? Boss, please help me take a look
